# Introdución a Python para Ciencia de Datos
## Python Numérico

<center>
    <img src="figures/python.jpg" width="500" />
</center>

# Numpy
- Operaciones numéricas básicas con arreglos (arrays) y matrices
- https://numpy.org/doc/stable/reference/index.html

# Creación de arreglos (arrays)

In [3]:
import numpy as np

m = [5, 7, 9, 11]
print( m, type(m) )

m = np.array(m)
print( m, type(m) )

print( m[1] )
print( m[2:] )

[5, 7, 9, 11] <class 'list'>
[ 5  7  9 11] <class 'numpy.ndarray'>
7
[ 9 11]


In [9]:
n = np.array( [[2, 4, 8], [5, 7, 9]] )
print(n)
print(n[0,1])
print(n[:,1])


[[2 4 8]
 [5 7 9]]
4
[4 7]
[]


In [16]:
a = np.arange(20)
print(a)

b = np.arange(2, 20, 3.1)
print(b)

c = np.linspace(1, 100, 10)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2.   5.1  8.2 11.3 14.4 17.5]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [18]:
print( np.random.randint(100, size=(20)) )
print( np.zeros(5) )
print( np.ones(5) )
print( np.ones((5, 5) ))

[75 72 66 64  6 99 67 86 83 45 10 75 42 99 84 77 43 44 25 80]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Manejo de arrays

In [20]:
u = np.array([12, 50, 0, 2, -3 , 11])

print( np.max(u) )
print( np.argmax(u) )


print( np.sort(u) )
print( np.argsort(u) )

50
1
[-3  0  2 11 12 50]
[4 2 3 5 0 1]


In [21]:
u = np.array([12, 5, 0, 2, -3 , 0])
w = np.array([24, 1, 0, 40, 0 , 5])

print( np.where(u > w, u, w) )
print( np.where(u > 10, u, u*10) ) 

print( np.count_nonzero(u))

[24  5  0 40  0  5]
[ 12  50   0  20 -30   0]
4


In [22]:
u = np.array([12, 5, 0, 2, -3 , 11])
w = np.array([24, 1, 0, 40, 0 , 5])

print( np.append(u, 4) )
print( np.append(u, w) )

a = []
for i in range(4):
    a.append(i**2)
print(a)

[12  5  0  2 -3 11  4]
[12  5  0  2 -3 11 24  1  0 40  0  5]
[0, 1, 4, 9]


In [93]:
a = np.array( [[2, 4, 8], [5, 7, 9]] )
b = np.array( [[6, 7, 0]] )

print( np.append(a, b) )
print( np.concatenate((a, b), axis=0) )

[2 4 8 5 7 9 6 7 0]
[[2 4 8]
 [5 7 9]
 [6 7 0]]


In [23]:
x = np.array([10, 21, 32, 39, 21, 11])
y = np.array([1, 1, 0, 1, 0, 1])
print(x[y == 0])
print(x[x > 20])

[32 21]
[21 32 39 21]


# Operaciones algebraicas

In [25]:
print( np.cos( np.deg2rad(45) ) )
print( np.log10(100) )
print( np.sqrt(9) )
print( 9**(1/2) )

0.7071067811865476
2.0
3.0
3.0


In [32]:
m = np.array([5, 7, 9, 11])
n = np.array([1, 3, 2, 3])
inner = np.inner(m, n)
outer = np.outer(m, n)
print(inner)
print(outer)

77
[[ 5 15 10 15]
 [ 7 21 14 21]
 [ 9 27 18 27]
 [11 33 22 33]]


In [40]:
print( np.floor(5.6) )
print( np.floor(5.1) )

print( np.round(5.1) )
print( np.round(5.6) )

5.0
5.0
5.0
6.0


In [54]:
a = np.array([[1, 2, 3], [3, 5, 6], [0, 5, 3]])
print(a*a)
a = np.matrix(a)
print(a*a)

[[ 1  4  9]
 [ 9 25 36]
 [ 0 25  9]]
[[ 7 27 24]
 [18 61 57]
 [15 40 39]]


# Operaciones numéricas

In [42]:
x = np.array([10, 18, 16, 20, 31, 29, 38])
y = np.array([0.5, 0.12, 0.14, 0.21, 0.17, 0.68, 0.95])
b1, b0 = np.polyfit(x, y, 1) #regresion lineal en numpy
b2, b1, b0 = np.polyfit(x, y, 2) #regresion lineal en numpy


In [26]:
a = np.array([[1, 2, 3], [3, 5, 6], [0, 5, 3]])
b = np.array([1, 2, 8])
x = np.linalg.solve(a, b)
print(x)

[-1.75  1.75 -0.25]


# Estadística básica

In [27]:
m = np.array([5, 7, 9, 11, 3, -3])
print(np.sum(m))
print(np.mean(m))
print(np.std(m))

32
5.333333333333333
4.533823502911814


In [28]:
m = np.array([5, 7, 9, 11, 3, -3, 15])
n = np.array([1, 4, 8, 19, 20, 3, 18])

print( np.corrcoef(m, n)[0][1] )
print( np.quantile(m, 0.25) )
print( np.quantile(m, 0.5) )

0.49932542644533595
4.0
7.0


# ¡Gracias por su atención!